self_see_links: 
  [
    {"name":"head_link","padding":0.09,}, 
    {"name":"chest_link",},
    {"name":"l_arm_el_y_link",},
    {"name":"l_arm_sh_p1_link",},
    {"name":"l_arm_sh_p2_link",},
    {"name":"l_arm_sh_r_link",},
    {"name":"l_arm_wr_p_link",},
    {"name":"l_arm_wr_r_link",},
    {"name":"l_arm_wr_y_link",},
    {"name":"l_leg_an_r_link",},
    {"name":"l_leg_foot_link",},
    {"name":"l_leg_hip_p_link",},
    {"name":"l_leg_hip_y_link",},
    {"name":"l_leg_kn_p_link",},
    {"name":"pelvis_link"},
    {"name":"r_arm_el_y_link",},
    {"name":"r_arm_sh_p1_link",},
    {"name":"r_arm_sh_p2_link",},
    {"name":"r_arm_sh_r_link",},
    {"name":"r_arm_wr_p_link",},
    {"name":"r_arm_wr_r_link",},
    {"name":"r_arm_wr_y_link",},
    {"name":"r_leg_an_r_link",},
    {"name":"r_leg_foot_link",},
    {"name":"r_leg_hip_p_link",},
    {"name":"r_leg_hip_y_link",},
    {"name":"r_leg_kn_p_link",}
  ]
